"""empty message

Revision ID: abfbdf5a3526
Revises: a5cffa318ac2
Create Date: 2025-04-07 14:59:59.703040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfbdf5a3526'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('img_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_character'),
    sa.UniqueConstraint('img_link'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('img_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_planet'),
    sa.UniqueConstraint('img_link'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite',
    sa.Column('id_fav', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id_character'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_fav')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
